"""adding role

Revision ID: 9a1c299f53be
Revises: f4ae7abcdaa4
Create Date: 2019-12-01 09:02:51.067454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1c299f53be'
down_revision = 'f4ae7abcdaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
